on:
  push:
    branches:
      - master

jobs:
  compile_index_job:
    runs-on: ubuntu-latest
    name: Compile latest index.html
    steps:
      - uses: actions/checkout@v2

      - name: Run compile script
        run: |
         ./compile_index.sh > index.html
         git rebase master pages

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update index.html
          branch: pages

